[package]
name = "ffi-ruby"
version = "0.1.0"
authors = ["Volodymyr Yevtushenko <volodymyr_yevtushenko@epam.com>"]
edition = "2018"
[dependencies]
actix-web = "1.0"
log = "0.4.0"
env_logger = "0.7.0"

[lib]
name = "fib"
crate-type = ["dylib"]
